Repository googleapis/java-storage-transfer, pull requests merged in 2021-09, with the labels that each got.

#33 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: storagetransfer

#36 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: storagetransfer

#45 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
  README.md
Labels: automerge, cla: yes, api: storagetransfer
