Repository googleapis/java-storage-transfer, pull requests merged in 2022-01, with the labels that each got.

#83 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: storagetransfer, owlbot:ignore

#88 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: storagetransfer, owlbot:ignore

#90 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: automerge, api: storagetransfer

#93 chore: correct .repo-metadata
  .repo-metadata.json
Labels: api: storagetransfer
